<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>26.1.0</Version>
    <Authors>cosmo0</Authors>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Label="ElectronNetCommon">
    <ElectronVersion>30.4.0</ElectronVersion>
    <ElectronSplashScreen>wwwroot\img\splash.png</ElectronSplashScreen>
    <ElectronIcon>wwwroot\favicon.ico</ElectronIcon>
    <ElectronPackageId>arcademanager</ElectronPackageId>
    <Description>A rom management tool to help you manage your arcade (MAME/FBNeo) rom collection.</Description>
    <License>https://github.com/cosmo0/arcade-manager/blob/master/LICENSE.md</License>
    <ProjectUrl>https://github.com/cosmo0/arcade-manager</ProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ArcadeManager.Core\ArcadeManager.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ElectronNET.Core" Version="0.5.1" />
    <PackageReference Include="ElectronNET.Core.AspNet" Version="0.5.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SimpleInjector" Version="5.6.0" />
    <PackageReference Include="SimpleInjector.Integration.AspNetCore.Mvc.Core" Version="5.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\Roms\" />
    <Folder Include="Views\Csv\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove=".DS_Store" />
    <None Remove="Assets\*.*" />
    <None Remove="Data\**\*.*" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Assets\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\Data\**\*.*">
      <Link>Data\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Update="Data\appdata.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\img\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>