name: ArcadeManager MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest  # For a list of available runner types, refer to
                           # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    defaults:
      run:
        working-directory: ./src

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x

    # Install the NodeJS workload
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 22.x

    # Restore Nuget packages
    - name: Restore dependencies
      run: dotnet restore

    # Build the app
    - name: Build
      env:
        SIXLABOR_LICENCE: ${{ secrets.SIXLABOR_LICENCE }}
      run: dotnet build -c Release --no-restore "-p:SixLaborsLicenseKey=${$SIXLABOR_LICENCE//;/%253B}"

    # Publish and package the app
    - name: Publish
      run: dotnet publish -p:PublishProfile=osx-arm64 --no-build -c Release -r osx-arm64
      working-directory: ./src/ArcadeManager

    # Upload the binaries of the GUI app
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: ArcadeManager-macos
        path: ./src/ArcadeManager/publish/Release/net10.0/osx-arm64/*.*

    # Upload the binaries of the console app
    - name: Upload console binaries
      uses: actions/upload-artifact@v4
      with:
        name: ArcadeManager-macos-console
        path: ./src/ArcadeManager.Console/bin/Release/net10.0/*.*
